### ISSUE TITLE
License

### ISSUE THREAD

**Issue by kwallis** [AmirHosseinCH/EmojiPicker#1]
Hello @AmirHosseinCH . I was wondering if you might consider assigning a specific license to your EmojiPicker project? Would you consider a permissive license such as MIT or BSD?

Please advise.

**Comment by AmirHosseinCH** [comment]
Hi, @kwallis . I added the MIT license to the repository.
However, keep in mind that this project has slight performance issues and is no longer being maintained.

**Comment by kwallis** [comment]
Thanks very much @AmirHosseinCH
